import { TableRow } from "@/components/admin-dashboard/AdminDashboardTable";

const recentLoginData: TableRow[] = [
  {
    id: "1",
    user: "John Doe",
    role: "Admin",
    school: "Elmwood Elementary School",
    date: "May 9, 2025",
    time: "9:00 AM",
    device: "Desktop - Chrome",
    admins: {
      names: ["John Doe"],
      more: 0,
    },
  },
  {
    id: "2",
    user: "Jane Smith",
    role: "Teacher",
    school: "Jefferson Middle School",
    date: "May 9, 2025",
    time: "8:45 AM",
    device: "Mobile - Safari",
    admins: {
      names: ["Jane Smith"],
      more: 0,
    },
  },
  {
    id: "3",
    user: "Robert Johnson",
    role: "Principal",
    school: "Lincoln Middle School",
    date: "May 9, 2025",
    time: "8:30 AM",
    device: "Tablet - Chrome",
    admins: {
      names: ["Robert Johnson"],
      more: 0,
    },
  },
  {
    id: "4",
    user: "Emily Davis",
    role: "Teacher",
    school: "Eastwood High School",
    date: "May 9, 2025",
    time: "8:15 AM",
    device: "Desktop - Firefox",
    admins: {
      names: ["Emily Davis"],
      more: 0,
    },
  },
  {
    id: "5",
    user: "Michael Wilson",
    role: "Admin",
    school: "Riverside Elementary School",
    date: "May 8, 2025",
    time: "4:30 PM",
    device: "Desktop - Edge",
    admins: {
      names: ["Michael Wilson"],
      more: 0,
    },
  },
  {
    id: "6",
    user: "Sarah Brown",
    role: "Teacher",
    school: "Westview High School",
    date: "May 8, 2025",
    time: "3:45 PM",
    device: "Mobile - Chrome",
    admins: {
      names: ["Sarah Brown"],
      more: 0,
    },
  },
  {
    id: "7",
    user: "David Miller",
    role: "Principal",
    school: "Northgate Middle School",
    date: "May 8, 2025",
    time: "2:30 PM",
    device: "Desktop - Chrome",
    admins: {
      names: ["David Miller"],
      more: 0,
    },
  },
  {
    id: "8",
    user: "Jennifer Taylor",
    role: "Teacher",
    school: "Pinecrest High School",
    date: "May 8, 2025",
    time: "1:15 PM",
    device: "Tablet - Safari",
    admins: {
      names: ["Jennifer Taylor"],
      more: 0,
    },
  },
  {
    id: "9",
    user: "James Anderson",
    role: "Admin",
    school: "George High School",
    date: "May 8, 2025",
    time: "11:00 AM",
    device: "Desktop - Chrome",
    admins: {
      names: ["James Anderson"],
      more: 0,
    },
  },
];
