import { TableRow } from "@/components/system-dashboard/DashboardTable";

// Sample data for Recent Logins tab
const loginData: TableRow[] = [
  {
    id: 1,
    userName: "John Smith",
    network: "Blue Ridge Charter Collaborative",
    district: "New York City Department of Education",
    role: "System Admin",
    lastLogin: "May 7, 2025 9:30 AM",
    loginCount: 42,
    device: "Desktop - Chrome",
  },
  {
    id: 2,
    userName: "Maria Lopez",
    network: "Cedar Grove Charter Network",
    district: "Los Angeles Unified School District",
    role: "Observer",
    lastLogin: "May 7, 2025 8:45 AM",
    loginCount: 87,
    device: "Mobile - Safari",
  },
  {
    id: 3,
    userName: "Robert Chen",
    network: "Charter Network",
    district: "Chicago Public Schools",
    role: "Admin",
    lastLogin: "May 6, 2025 3:22 PM",
    loginCount: 33,
    device: "Tablet - Chrome",
  },
  {
    id: 4,
    userName: "Sarah Johnson",
    network: "Charter Network",
    district: "Clark County School District",
    role: "Observer",
    lastLogin: "May 6, 2025 11:05 AM",
    loginCount: 126,
    device: "Desktop - Firefox",
  },
  {
    id: 5,
    userName: "David Miller",
    network: "None",
    district: "Broward County Public Schools",
    role: "System Admin",
    lastLogin: "May 5, 2025 4:17 PM",
    loginCount: 58,
    device: "Desktop - Edge",
  },
  {
    id: 6,
    userName: "Jessica Williams",
    network: "None",
    district: "Houston Independent School District",
    role: "Observer",
    lastLogin: "May 5, 2025 1:30 PM",
    loginCount: 92,
    device: "Mobile - Chrome",
  },
  {
    id: 7,
    userName: "Michael Davis",
    network: "Foundations Education Collaborative",
    district: "Hawaii Department of Education",
    role: "Admin",
    lastLogin: "May 4, 2025 9:12 AM",
    loginCount: 41,
    device: "Desktop - Safari",
  },
  {
    id: 8,
    userName: "Jennifer Lee",
    network: "None",
    district: "Orange County Public Schools",
    role: "Observer",
    lastLogin: "May 3, 2025 10:45 AM",
    loginCount: 75,
    device: "Tablet - Safari",
  },
  {
    id: 9,
    userName: "Thomas Brown",
    network: "Pinnacle Charter Network",
    district: "School District of Palm Beach County",
    role: "System Admin",
    lastLogin: "May 3, 2025 8:30 AM",
    loginCount: 103,
    device: "Desktop - Chrome",
  },
];
